[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-snowflake>=1.10.3",
]

[dependency-groups]
dev = [
    "sqlfluff>=3.5.0",
    "sqlfluff-templater-dbt>=3.5.0",
]
